import React, { useState } from 'react'
import { Share2, Download, Eye } from 'lucide-react'
import Button from './Button'
import Card from './Card'
import { useApp } from '../context/AppContext'
import { aiService } from '../services/openai'
import { geolocationService } from '../services/geolocation'

export default function ShareCardGenerator({ variant = 'preview' }) {
  const [isGenerating, setIsGenerating] = useState(false)
  const [generatedCard, setGeneratedCard] = useState(null)
  const [includeLocation, setIncludeLocation] = useState(true)
  const [includeRights, setIncludeRights] = useState(true)
  const [customMessage, setCustomMessage] = useState('')
  const { state } = useApp()

  const generateSummaryCard = async () => {
    setIsGenerating(true)
    
    try {
      let locationData = null
      
      if (includeLocation) {
        try {
          locationData = await geolocationService.getLocationWithAddress()
        } catch (error) {
          console.warn('Could not get location:', error.message)
          locationData = { address: { formatted: 'Location unavailable' } }
        }
      }

      const incidentData = {
        timestamp: new Date().toISOString(),
        location: locationData?.address?.formatted || 'Location not shared',
        type: 'general',
        notes: customMessage
      }

      const summaryCard = await aiService.generateSummaryCard(
        incidentData, 
        state.selectedState || 'General'
      )

      const card = {
        id: Date.now().toString(),
        timestamp: summaryCard.timestamp,
        state: state.selectedState || 'General',
        location: includeLocation ? summaryCard.location : 'Location hidden',
        keyRights: includeRights ? [
          'Right to remain silent',
          'Right to refuse searches without warrant',
          'Right to ask if you are free to leave',
          'Right to have an attorney present'
        ] : [],
        customMessage: customMessage,
        emergencyContacts: state.trustedContacts.length,
        aiSummary: summaryCard.summary,
        keyPoints: summaryCard.keyPoints
      }
      
      setGeneratedCard(card)
    } catch (error) {
      console.error('Error generating summary card:', error)
      // Fallback to basic card
      const card = {
        id: Date.now().toString(),
        timestamp: new Date().toISOString(),
        state: state.selectedState || 'Unknown',
        location: includeLocation ? 'Current Location' : 'Location hidden',
        keyRights: includeRights ? [
          'Right to remain silent',
          'Right to refuse searches without warrant',
          'Right to ask if you are free to leave',
          'Right to have an attorney present'
        ] : [],
        customMessage: customMessage,
        emergencyContacts: state.trustedContacts.length
      }
      setGeneratedCard(card)
    } finally {
      setIsGenerating(false)
    }
  }

  const shareCard = async () => {
    if (!generatedCard) return

    const shareText = `Know Your Rights Summary - ${generatedCard.state}\n\nKey Rights:\n${generatedCard.keyRights.map(right => `• ${right}`).join('\n')}\n\n${generatedCard.customMessage}\n\nGenerated by Know Your Rights Buddy`

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Know Your Rights Summary',
          text: shareText,
        })
      } catch (error) {
        console.log('Share cancelled or failed')
      }
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(shareText)
      alert('Summary copied to clipboard!')
    }
  }

  const downloadCard = () => {
    if (!generatedCard) return

    const cardData = JSON.stringify(generatedCard, null, 2)
    const blob = new Blob([cardData], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `rights-summary-${generatedCard.timestamp}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  if (variant === 'config') {
    return (
      <Card variant="plain" className="space-y-6">
        <h3 className="text-xl font-bold text-gray-900">Configure Summary Card</h3>
        
        <div className="space-y-4">
          <div className="flex items-center space-x-3">
            <input
              type="checkbox"
              id="includeLocation"
              checked={includeLocation}
              onChange={(e) => setIncludeLocation(e.target.checked)}
              className="rounded border-gray-300"
            />
            <label htmlFor="includeLocation" className="text-gray-700">
              Include current location
            </label>
          </div>

          <div className="flex items-center space-x-3">
            <input
              type="checkbox"
              id="includeRights"
              checked={includeRights}
              onChange={(e) => setIncludeRights(e.target.checked)}
              className="rounded border-gray-300"
            />
            <label htmlFor="includeRights" className="text-gray-700">
              Include key rights summary
            </label>
          </div>

          <div>
            <label htmlFor="customMessage" className="block text-sm font-medium text-gray-700 mb-2">
              Custom message (optional)
            </label>
            <textarea
              id="customMessage"
              value={customMessage}
              onChange={(e) => setCustomMessage(e.target.value)}
              placeholder="Add any additional information..."
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
              rows={3}
            />
          </div>
        </div>

        <Button
          onClick={generateSummaryCard}
          disabled={isGenerating}
          className="w-full"
        >
          {isGenerating ? 'Generating...' : 'Generate Summary Card'}
        </Button>
      </Card>
    )
  }

  return (
    <div className="space-y-6">
      {!generatedCard && (
        <Card variant="plain" className="text-center">
          <Eye className="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-xl font-bold text-gray-900 mb-2">
            Generate Summary Card
          </h3>
          <p className="text-gray-600 mb-6">
            Create a shareable summary of your rights and current situation
          </p>
          <Button onClick={generateSummaryCard} disabled={isGenerating}>
            {isGenerating ? 'Generating...' : 'Create Summary'}
          </Button>
        </Card>
      )}

      {generatedCard && (
        <Card variant="elevated" className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xl font-bold text-gray-900">Rights Summary</h3>
            <span className="text-sm text-gray-500">
              {new Date(generatedCard.timestamp).toLocaleString()}
            </span>
          </div>

          <div className="space-y-3">
            <div>
              <strong className="text-gray-700">State:</strong> {generatedCard.state}
            </div>
            <div>
              <strong className="text-gray-700">Location:</strong> {generatedCard.location}
            </div>
            
            {generatedCard.keyRights.length > 0 && (
              <div>
                <strong className="text-gray-700">Key Rights:</strong>
                <ul className="mt-2 space-y-1">
                  {generatedCard.keyRights.map((right, index) => (
                    <li key={index} className="text-gray-600 text-sm">
                      • {right}
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {generatedCard.customMessage && (
              <div>
                <strong className="text-gray-700">Message:</strong>
                <p className="text-gray-600 text-sm mt-1">{generatedCard.customMessage}</p>
              </div>
            )}

            <div>
              <strong className="text-gray-700">Emergency Contacts:</strong> {generatedCard.emergencyContacts} configured
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t">
            <Button onClick={shareCard} variant="primary" className="flex-1">
              <Share2 className="h-4 w-4 mr-2" />
              Share
            </Button>
            <Button onClick={downloadCard} variant="secondary" className="flex-1">
              <Download className="h-4 w-4 mr-2" />
              Download
            </Button>
            <Button 
              onClick={() => setGeneratedCard(null)} 
              variant="secondary"
              className="flex-1"
            >
              Generate New
            </Button>
          </div>
        </Card>
      )}
    </div>
  )
}
